services:
  db:
    container_name: db 
    image: postgres:latest
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=REMOVED_SECRET
    volumes:
      - ./init_pg_dbs.sql:/docker-entrypoint-initdb.d/init_pg_dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5